# Generated by Django 5.1.4 on 2025-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0003_contactus_about_office_about_projects_about_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About Us', max_length=200),
        ),
    ]
