# Generated by Django 5.1.5 on 2025-02-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0004_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='ماذا عنا', max_length=200),
        ),
    ]
