# Generated by Django 5.1.5 on 2025-02-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0005_businessgallery_delete_backgroundimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='office',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='about',
            name='workers',
            field=models.IntegerField(default=0),
        ),
    ]
