# Generated by Django 5.1.5 on 2025-02-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0006_alter_about_office_alter_about_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='project_count',
            field=models.CharField(default='عدد المشاريع', max_length=200),
        ),
    ]
