# Generated by Django 5.1.5 on 2025-02-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0007_about_project_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessgallery',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
