# Generated by Django 5.1.5 on 2025-02-03 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0008_alter_businessgallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgallery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
