# Generated by Django 5.1.5 on 2025-02-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0009_businessgallery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessgallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
