# Generated by Django 5.1.5 on 2025-02-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0010_alter_businessgallery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_link',
            field=models.URLField(default='https://drive.google.com/file/d/1P_UBPWF6hiK5M_Jqd4D5LHFD6Tq_X8RG/view'),
        ),
    ]
