# Generated by Django 5.1.5 on 2025-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0012_contactus_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='intro_content',
            field=models.TextField(default='هي واحدة من الشركات الرائدة في مجال التشطيبات والديكورات، حيث نقدم حلول تصميم هندسية مبتكرة ومتخصصة للمساحات الداخلية والخارجية. نحن نسعى جاهدين لتحقيق أعلى معايير الجودة في جميع مشاريعنا، مع التركيز على الابتكار والإبداع في كل تفصيلة. بالإضافة إلى ذلك، نقدم خدمات المقاولات العامة ملتزمين بتوفير بيئات عمل عملية وجميلة تلبي جميع احتياجات عملائنا وتتفوق على توقعاتهم.'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_content',
            field=models.TextField(default='في شركة إبداع للتصميم، نفخر بإنجاز أكثر من خمسين مشروعًا بنجاح في مجالات التشطيبات والديكورات. نحن نلتزم بتقديم حلول تصميم مبتكرة تلبي احتياجات عملائنا وتتفوق على توقعاتهم، مع ضمان أعلى مستويات الجودة والاحترافية في كل مشروع.'),
        ),
    ]
