# Generated by Django 5.1.5 on 2025-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebda3', '0013_alter_about_img_alter_about_intro_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='office',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='about',
            name='project_count',
            field=models.CharField(default='خمسين', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='projects',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='about',
            name='users',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='about',
            name='workers',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=100086633168247'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='instgram',
            field=models.URLField(default='https://www.instagram.com/ebda3designegy/'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='location_url',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/XzVRa8YikcjNSJ3Y7', null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(default='ماذا عنا', max_length=200),
        ),
    ]
